// @ts-expect-error — generated by scripts/patch-sql-wasm.mjs
import initSqlJs from '../vendor/sql-wasm.mjs'
import type { Database, SqlJsStatic } from 'fts5-sql-bundle'

let SQL: SqlJsStatic | null = null
let db: Database | null = null

async function loadCorpusBuffer(): Promise<ArrayBuffer> {
  const gz = await fetch('/corpus/egw.sqlite.gz')
  if (gz.ok && typeof DecompressionStream !== 'undefined') {
    const stream = gz.body!.pipeThrough(new DecompressionStream('gzip'))
    return new Response(stream).arrayBuffer()
  }

  const res = await fetch('/corpus/egw.sqlite')
  if (!res.ok) {
    throw new Error('Corpus not found. Run: npm run corpus:build')
  }
  return res.arrayBuffer()
}

async function ensureDb(): Promise<Database> {
  if (db) return db

  SQL = await initSqlJs({
    locateFile: (file: string) => `/wasm/${file}`,
  })

  const buffer = await loadCorpusBuffer()
  db = new SQL!.Database(new Uint8Array(buffer))
  return db
}

function buildFtsQuery(raw: string): string {
  const trimmed = raw.trim()
  if (!trimmed) return ''
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) return trimmed

  const terms = trimmed
    .split(/\s+/)
    .map((t) => t.replace(/[^\w'-]/g, ''))
    .filter(Boolean)

  if (terms.length === 0) return ''
  return terms.map((t) => `"${t}"*`).join(' AND ')
}

export interface BookRow {
  id: string
  code: string
  title: string
  year: number | null
  chapter_count: number
  paragraph_count: number
}

export interface ChapterRow {
  id: number
  book_id: string
  number: number
  title: string
}

export interface ParagraphRow {
  id: number
  book_id: string
  chapter_id: number
  chapter_num: number
  page_num: number
  para_num: number
  reference: string
  text: string
}

export interface SearchHit {
  id: number
  book_id: string
  book_title: string
  book_code: string
  chapter_num: number
  chapter_title: string
  para_num: number
  reference: string
  text: string
  snippet: string
  rank: number
}

export async function initCorpusEngine() {
  const database = await ensureDb()
  const books = database.exec('SELECT COUNT(*) FROM books')[0]?.values[0]?.[0] ?? 0
  const paras = database.exec('SELECT COUNT(*) FROM paragraphs')[0]?.values[0]?.[0] ?? 0
  return {
    bookCount: Number(books),
    paragraphCount: Number(paras),
  }
}

export async function searchCorpus(
  query: string,
  limit = 30,
  bookId?: string,
): Promise<SearchHit[]> {
  const database = await ensureDb()
  const ftsQuery = buildFtsQuery(query)
  if (!ftsQuery) return []

  const bookFilter = bookId ? 'AND p.book_id = ?' : ''
  const params: (string | number)[] = bookId ? [ftsQuery, bookId, limit] : [ftsQuery, limit]

  const sql = `
    SELECT
      p.id,
      p.book_id,
      b.title AS book_title,
      b.code AS book_code,
      p.chapter_num,
      c.title AS chapter_title,
      p.para_num,
      p.reference,
      p.text,
      snippet(paragraphs_fts, 1, '<mark>', '</mark>', '…', 24) AS snippet,
      bm25(paragraphs_fts) AS rank
    FROM paragraphs_fts
    JOIN paragraphs p ON paragraphs_fts.rowid = p.id
    JOIN books b ON p.book_id = b.id
    JOIN chapters c ON p.chapter_id = c.id
    WHERE paragraphs_fts MATCH ?
    ${bookFilter}
    ORDER BY rank
    LIMIT ?
  `

  const stmt = database.prepare(sql)
  stmt.bind(params)

  const results: SearchHit[] = []
  while (stmt.step()) {
    const row = stmt.getAsObject() as Record<string, string | number>
    results.push({
      id: Number(row.id),
      book_id: String(row.book_id),
      book_title: String(row.book_title),
      book_code: String(row.book_code),
      chapter_num: Number(row.chapter_num),
      chapter_title: String(row.chapter_title),
      para_num: Number(row.para_num),
      reference: String(row.reference),
      text: String(row.text),
      snippet: String(row.snippet),
      rank: Number(row.rank),
    })
  }
  stmt.free()
  return results
}

export async function getBooks(): Promise<BookRow[]> {
  const database = await ensureDb()
  const res = database.exec(`
    SELECT id, code, title, year, chapter_count, paragraph_count
    FROM books ORDER BY title
  `)
  if (!res[0]) return []
  return res[0].values.map((row) => ({
    id: String(row[0]),
    code: String(row[1]),
    title: String(row[2]),
    year: row[3] == null ? null : Number(row[3]),
    chapter_count: Number(row[4]),
    paragraph_count: Number(row[5]),
  }))
}

export async function getChapters(bookId: string): Promise<ChapterRow[]> {
  const database = await ensureDb()
  const stmt = database.prepare(`
    SELECT id, book_id, number, title FROM chapters
    WHERE book_id = ? ORDER BY number
  `)
  stmt.bind([bookId])
  const rows: ChapterRow[] = []
  while (stmt.step()) {
    const r = stmt.getAsObject() as Record<string, string | number>
    rows.push({
      id: Number(r.id),
      book_id: String(r.book_id),
      number: Number(r.number),
      title: String(r.title),
    })
  }
  stmt.free()
  return rows
}

export async function getChapterParagraphs(
  bookId: string,
  chapterNum: number,
): Promise<ParagraphRow[]> {
  const database = await ensureDb()
  const stmt = database.prepare(`
    SELECT id, book_id, chapter_id, chapter_num, page_num, para_num, reference, text
    FROM paragraphs
    WHERE book_id = ? AND chapter_num = ?
    ORDER BY page_num, para_num
  `)
  stmt.bind([bookId, chapterNum])
  const rows: ParagraphRow[] = []
  while (stmt.step()) {
    const r = stmt.getAsObject() as Record<string, string | number>
    rows.push({
      id: Number(r.id),
      book_id: String(r.book_id),
      chapter_id: Number(r.chapter_id),
      chapter_num: Number(r.chapter_num),
      page_num: Number(r.page_num),
      para_num: Number(r.para_num),
      reference: String(r.reference),
      text: String(r.text),
    })
  }
  stmt.free()
  return rows
}

export async function getParagraph(id: number): Promise<ParagraphRow | null> {
  const database = await ensureDb()
  const stmt = database.prepare(`
    SELECT id, book_id, chapter_id, chapter_num, page_num, para_num, reference, text
    FROM paragraphs WHERE id = ?
  `)
  stmt.bind([id])
  if (!stmt.step()) {
    stmt.free()
    return null
  }
  const r = stmt.getAsObject() as Record<string, string | number>
  stmt.free()
  return {
    id: Number(r.id),
    book_id: String(r.book_id),
    chapter_id: Number(r.chapter_id),
    chapter_num: Number(r.chapter_num),
    page_num: Number(r.page_num),
    para_num: Number(r.para_num),
    reference: String(r.reference),
    text: String(r.text),
  }
}

export function parseReference(input: string): {
  code: string
  page: number
  para: number
} | null {
  const trimmed = input.trim()
  const match = trimmed.match(/^([A-Za-z]{1,5}\d?[A-Za-z]?)\s*(\d+)\.(\d+)\.?$/)
  if (!match) return null
  return {
    code: match[1]!.toUpperCase(),
    page: Number.parseInt(match[2]!, 10),
    para: Number.parseInt(match[3]!, 10),
  }
}

function rowToParagraph(r: Record<string, string | number>): ParagraphRow {
  return {
    id: Number(r.id),
    book_id: String(r.book_id),
    chapter_id: Number(r.chapter_id),
    chapter_num: Number(r.chapter_num),
    page_num: Number(r.page_num),
    para_num: Number(r.para_num),
    reference: String(r.reference),
    text: String(r.text),
  }
}

export async function lookupByReference(ref: string): Promise<ParagraphRow | null> {
  const database = await ensureDb()
  const parsed = parseReference(ref)

  if (parsed) {
    const stmt = database.prepare(`
      SELECT p.id, p.book_id, p.chapter_id, p.chapter_num, p.page_num, p.para_num, p.reference, p.text
      FROM paragraphs p
      JOIN books b ON p.book_id = b.id
      WHERE UPPER(b.code) = ? AND p.page_num = ? AND p.para_num = ?
      LIMIT 1
    `)
    stmt.bind([parsed.code, parsed.page, parsed.para])
    if (stmt.step()) {
      const row = rowToParagraph(stmt.getAsObject() as Record<string, string | number>)
      stmt.free()
      return row
    }
    stmt.free()
  }

  const normalized = ref.trim().replace(/\s+/g, ' ')
  const stmt = database.prepare(`
    SELECT id, book_id, chapter_id, chapter_num, page_num, para_num, reference, text
    FROM paragraphs
    WHERE UPPER(reference) = UPPER(?)
    LIMIT 1
  `)
  stmt.bind([normalized])
  if (stmt.step()) {
    const row = rowToParagraph(stmt.getAsObject() as Record<string, string | number>)
    stmt.free()
    return row
  }
  stmt.free()
  return null
}
