// @ts-expect-error — generated by scripts/patch-sql-wasm.mjs
import initSqlJs from '../vendor/sql-wasm.mjs'
import type { Database, SqlJsStatic } from 'fts5-sql-bundle'
import {
  isPioneerBookId,
  PIONEER_PARAGRAPH_OFFSET,
  type BookCollection,
} from '../lib/corpusConstants'

let SQL: SqlJsStatic | null = null
let egwDb: Database | null = null
let pioneerDb: Database | null = null

function isGzipBuffer(buf: ArrayBuffer): boolean {
  const bytes = new Uint8Array(buf)
  return bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b
}

function isSqliteBuffer(buf: ArrayBuffer): boolean {
  const bytes = new Uint8Array(buf)
  if (bytes.length < 16) return false
  return new TextDecoder().decode(bytes.slice(0, 15)) === 'SQLite format 3'
}

async function decompressGzip(buf: ArrayBuffer): Promise<ArrayBuffer> {
  if (typeof DecompressionStream === 'undefined') {
    throw new Error('Gzip corpus requires DecompressionStream (use a modern browser)')
  }
  const stream = new Response(buf).body!.pipeThrough(new DecompressionStream('gzip'))
  return new Response(stream).arrayBuffer()
}

async function fetchCorpusBuffer(basePath: string): Promise<ArrayBuffer | null> {
  try {
    const gz = await fetch(`${basePath}.gz`)
    if (gz.ok) {
      const buf = await gz.arrayBuffer()
      if (isGzipBuffer(buf)) return decompressGzip(buf)
      if (isSqliteBuffer(buf)) return buf
    }
  } catch {
    // fall through
  }

  try {
    const res = await fetch(basePath)
    if (!res.ok) return null
    const buf = await res.arrayBuffer()
    return isSqliteBuffer(buf) ? buf : null
  } catch {
    return null
  }
}

async function ensureSql(): Promise<SqlJsStatic> {
  if (!SQL) {
    SQL = await initSqlJs({
      locateFile: (file: string) => `/wasm/${file}`,
    })
  }
  return SQL!
}

async function ensureEgwDb(): Promise<Database> {
  if (egwDb) return egwDb

  const SQL = await ensureSql()
  const buffer = await fetchCorpusBuffer('/corpus/egw.sqlite')
  if (!buffer) {
    throw new Error('EGW corpus not found. Run: npm run corpus:build')
  }

  egwDb = new SQL.Database(new Uint8Array(buffer))
  return egwDb
}

export function isPioneerCorpusReady(): boolean {
  return pioneerDb !== null
}

export async function attachPioneerCorpus(buffer: ArrayBuffer): Promise<void> {
  if (pioneerDb) return
  const SQL = await ensureSql()
  if (!isSqliteBuffer(buffer)) {
    throw new Error('Invalid pioneer corpus file')
  }
  pioneerDb = new SQL.Database(new Uint8Array(buffer))
}

export function pioneerCorpusAvailable(): Promise<boolean> {
  return fetch('/corpus/pioneers-manifest.json', { method: 'HEAD' })
    .then((r) => r.ok)
    .catch(() => false)
}

function dbForBook(bookId: string): Database {
  if (isPioneerBookId(bookId)) {
    if (!pioneerDb) throw new Error('Pioneer library still downloading')
    return pioneerDb
  }
  if (!egwDb) throw new Error('Corpus not loaded')
  return egwDb
}

function dbForParagraph(paragraphId: number, bookId?: string): Database {
  if (bookId) return dbForBook(bookId)
  if (paragraphId >= PIONEER_PARAGRAPH_OFFSET) {
    if (!pioneerDb) throw new Error('Pioneer library still downloading')
    return pioneerDb
  }
  if (!egwDb) throw new Error('Corpus not loaded')
  return egwDb
}

function buildFtsQuery(raw: string): string {
  const trimmed = raw.trim()
  if (!trimmed) return ''
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) return trimmed

  const terms = trimmed
    .split(/\s+/)
    .map((t) => t.replace(/[^\w'-]/g, ''))
    .filter(Boolean)

  if (terms.length === 0) return ''
  return terms.map((t) => `"${t}"*`).join(' AND ')
}

export interface BookRow {
  id: string
  code: string
  title: string
  author: string
  collection: BookCollection
  year: number | null
  chapter_count: number
  paragraph_count: number
}

export interface ChapterRow {
  id: number
  book_id: string
  number: number
  title: string
}

export interface ParagraphRow {
  id: number
  book_id: string
  chapter_id: number
  chapter_num: number
  page_num: number
  para_num: number
  reference: string
  text: string
}

export interface SearchHit {
  id: number
  book_id: string
  book_title: string
  book_code: string
  book_author: string
  collection: BookCollection
  chapter_num: number
  chapter_title: string
  para_num: number
  reference: string
  text: string
  snippet: string
  rank: number
}

interface BooksSchema {
  hasAuthor: boolean
  hasCollection: boolean
  hasPuborder: boolean
}

const schemaCache = new WeakMap<Database, BooksSchema>()

function getBooksSchema(database: Database): BooksSchema {
  const cached = schemaCache.get(database)
  if (cached) return cached

  const bookInfo = database.exec('PRAGMA table_info(books)')
  const bookCols = new Set(bookInfo[0]?.values.map((row) => String(row[1])) ?? [])
  const paraInfo = database.exec('PRAGMA table_info(paragraphs)')
  const paraCols = new Set(paraInfo[0]?.values.map((row) => String(row[1])) ?? [])

  const schema: BooksSchema = {
    hasAuthor: bookCols.has('author'),
    hasCollection: bookCols.has('collection'),
    hasPuborder: paraCols.has('puborder'),
  }
  schemaCache.set(database, schema)
  return schema
}

function authorExpr(database: Database, alias = ''): string {
  const col = alias ? `${alias}.author` : 'author'
  return getBooksSchema(database).hasAuthor
    ? `COALESCE(${col}, 'Ellen G. White')`
    : `'Ellen G. White'`
}

function collectionExpr(database: Database, fallback: BookCollection, alias = ''): string {
  const col = alias ? `${alias}.collection` : 'collection'
  return getBooksSchema(database).hasCollection
    ? `COALESCE(${col}, '${fallback}')`
    : `'${fallback}'`
}

function bookSelectSql(database: Database): string {
  return `
    SELECT id, code, title,
      ${authorExpr(database)} AS author,
      ${collectionExpr(database, 'egw')} AS collection,
      year, chapter_count, paragraph_count
    FROM books
  `
}

function paragraphOrderSql(database: Database): string {
  return getBooksSchema(database).hasPuborder
    ? 'puborder, page_num, para_num'
    : 'page_num, para_num'
}

function mapBookRow(row: (string | number | null)[]): BookRow {
  return {
    id: String(row[0]),
    code: String(row[1]),
    title: String(row[2]),
    author: String(row[3]),
    collection: String(row[4]) as BookCollection,
    year: row[5] == null ? null : Number(row[5]),
    chapter_count: Number(row[6]),
    paragraph_count: Number(row[7]),
  }
}

function readBooksFromDb(database: Database): BookRow[] {
  const res = database.exec(`${bookSelectSql(database)} ORDER BY title`)
  if (!res[0]) return []
  return res[0].values.map((row) => mapBookRow(row as (string | number | null)[]))
}

function searchOneDb(
  database: Database,
  ftsQuery: string,
  collection: BookCollection,
  limit: number,
  bookId?: string,
): SearchHit[] {
  const bookFilter = bookId ? 'AND p.book_id = ?' : ''
  const params: (string | number)[] = bookId
    ? [ftsQuery, bookId, limit]
    : [ftsQuery, limit]

  const sql = `
    SELECT
      p.id,
      p.book_id,
      b.title AS book_title,
      b.code AS book_code,
      ${authorExpr(database, 'b')} AS book_author,
      ${collectionExpr(database, collection, 'b')} AS collection,
      p.chapter_num,
      c.title AS chapter_title,
      p.para_num,
      p.reference,
      p.text,
      snippet(paragraphs_fts, 1, '<mark>', '</mark>', '…', 24) AS snippet,
      bm25(paragraphs_fts) AS rank
    FROM paragraphs_fts
    JOIN paragraphs p ON paragraphs_fts.rowid = p.id
    JOIN books b ON p.book_id = b.id
    JOIN chapters c ON p.chapter_id = c.id
    WHERE paragraphs_fts MATCH ?
    ${bookFilter}
    ORDER BY rank
    LIMIT ?
  `

  const stmt = database.prepare(sql)
  stmt.bind(params)

  const results: SearchHit[] = []
  while (stmt.step()) {
    const row = stmt.getAsObject() as Record<string, string | number>
    results.push({
      id: Number(row.id),
      book_id: String(row.book_id),
      book_title: String(row.book_title),
      book_code: String(row.book_code),
      book_author: String(row.book_author),
      collection: String(row.collection) as BookCollection,
      chapter_num: Number(row.chapter_num),
      chapter_title: String(row.chapter_title),
      para_num: Number(row.para_num),
      reference: String(row.reference),
      text: String(row.text),
      snippet: String(row.snippet),
      rank: Number(row.rank),
    })
  }
  stmt.free()
  return results
}

export async function initCorpusEngine() {
  const database = await ensureEgwDb()
  const books = database.exec('SELECT COUNT(*) FROM books')[0]?.values[0]?.[0] ?? 0
  const paras = database.exec('SELECT COUNT(*) FROM paragraphs')[0]?.values[0]?.[0] ?? 0
  return {
    bookCount: Number(books),
    paragraphCount: Number(paras),
  }
}

export async function searchCorpus(
  query: string,
  limit = 30,
  bookId?: string,
  collection?: BookCollection | 'all',
): Promise<SearchHit[]> {
  await ensureEgwDb()
  const ftsQuery = buildFtsQuery(query)
  if (!ftsQuery) return []

  const wantEgw = collection !== 'pioneer' && (!bookId || !isPioneerBookId(bookId))
  const wantPioneer =
    collection !== 'egw' && pioneerDb && (!bookId || isPioneerBookId(bookId))

  const hits: SearchHit[] = []

  if (wantEgw) {
    hits.push(...searchOneDb(egwDb!, ftsQuery, 'egw', limit, bookId))
  }
  if (wantPioneer) {
    hits.push(...searchOneDb(pioneerDb!, ftsQuery, 'pioneer', limit, bookId))
  }

  hits.sort((a, b) => a.rank - b.rank)
  return hits.slice(0, limit)
}

export async function getBooks(collection?: BookCollection | 'all'): Promise<BookRow[]> {
  await ensureEgwDb()
  const rows: BookRow[] = []

  if (collection !== 'pioneer') {
    rows.push(...readBooksFromDb(egwDb!))
  }
  if (collection !== 'egw' && pioneerDb) {
    rows.push(...readBooksFromDb(pioneerDb))
  }

  return rows.sort((a, b) => a.title.localeCompare(b.title))
}

export async function getBook(bookId: string): Promise<BookRow | null> {
  await ensureEgwDb()
  const database = dbForBook(bookId)
  const stmt = database.prepare(`${bookSelectSql(database)} WHERE id = ?`)
  stmt.bind([bookId])
  if (!stmt.step()) {
    stmt.free()
    return null
  }
  const row = stmt.getAsObject() as Record<string, string | number | null>
  stmt.free()
  return {
    id: String(row.id),
    code: String(row.code),
    title: String(row.title),
    author: String(row.author ?? 'Ellen G. White'),
    collection: String(row.collection ?? 'egw') as BookCollection,
    year: row.year == null ? null : Number(row.year),
    chapter_count: Number(row.chapter_count),
    paragraph_count: Number(row.paragraph_count),
  }
}

export async function getChapters(bookId: string): Promise<ChapterRow[]> {
  await ensureEgwDb()
  const database = dbForBook(bookId)
  const stmt = database.prepare(`
    SELECT id, book_id, number, title FROM chapters
    WHERE book_id = ? ORDER BY number
  `)
  stmt.bind([bookId])
  const rows: ChapterRow[] = []
  while (stmt.step()) {
    const r = stmt.getAsObject() as Record<string, string | number>
    rows.push({
      id: Number(r.id),
      book_id: String(r.book_id),
      number: Number(r.number),
      title: String(r.title),
    })
  }
  stmt.free()
  return rows
}

export async function getChapterParagraphs(
  bookId: string,
  chapterNum: number,
): Promise<ParagraphRow[]> {
  await ensureEgwDb()
  const database = dbForBook(bookId)
  const order = paragraphOrderSql(database)
  const stmt = database.prepare(`
    SELECT id, book_id, chapter_id, chapter_num, page_num, para_num, reference, text
    FROM paragraphs
    WHERE book_id = ? AND chapter_num = ?
    ORDER BY ${order}
  `)
  stmt.bind([bookId, chapterNum])
  const rows: ParagraphRow[] = []
  while (stmt.step()) {
    const r = stmt.getAsObject() as Record<string, string | number>
    rows.push({
      id: Number(r.id),
      book_id: String(r.book_id),
      chapter_id: Number(r.chapter_id),
      chapter_num: Number(r.chapter_num),
      page_num: Number(r.page_num),
      para_num: Number(r.para_num),
      reference: String(r.reference),
      text: String(r.text),
    })
  }
  stmt.free()
  return rows
}

export async function getParagraph(id: number, bookId?: string): Promise<ParagraphRow | null> {
  await ensureEgwDb()
  const database = dbForParagraph(id, bookId)
  const stmt = database.prepare(`
    SELECT id, book_id, chapter_id, chapter_num, page_num, para_num, reference, text
    FROM paragraphs WHERE id = ?
  `)
  stmt.bind([id])
  if (!stmt.step()) {
    stmt.free()
    return null
  }
  const r = stmt.getAsObject() as Record<string, string | number>
  stmt.free()
  return {
    id: Number(r.id),
    book_id: String(r.book_id),
    chapter_id: Number(r.chapter_id),
    chapter_num: Number(r.chapter_num),
    page_num: Number(r.page_num),
    para_num: Number(r.para_num),
    reference: String(r.reference),
    text: String(r.text),
  }
}

export function parseReference(input: string): {
  code: string
  page: number
  para: number
} | null {
  const trimmed = input.trim()
  const match = trimmed.match(/^([A-Za-z]{1,5}\d?[A-Za-z]?)\s*(\d+)\.(\d+)\.?$/)
  if (!match) return null
  return {
    code: match[1]!.toUpperCase(),
    page: Number.parseInt(match[2]!, 10),
    para: Number.parseInt(match[3]!, 10),
  }
}

function rowToParagraph(r: Record<string, string | number>): ParagraphRow {
  return {
    id: Number(r.id),
    book_id: String(r.book_id),
    chapter_id: Number(r.chapter_id),
    chapter_num: Number(r.chapter_num),
    page_num: Number(r.page_num),
    para_num: Number(r.para_num),
    reference: String(r.reference),
    text: String(r.text),
  }
}

function lookupInDb(database: Database, ref: string, parsed: ReturnType<typeof parseReference>) {
  if (parsed) {
    const stmt = database.prepare(`
      SELECT p.id, p.book_id, p.chapter_id, p.chapter_num, p.page_num, p.para_num, p.reference, p.text
      FROM paragraphs p
      JOIN books b ON p.book_id = b.id
      WHERE UPPER(b.code) = ? AND p.page_num = ? AND p.para_num = ?
      LIMIT 1
    `)
    stmt.bind([parsed.code, parsed.page, parsed.para])
    if (stmt.step()) {
      const row = rowToParagraph(stmt.getAsObject() as Record<string, string | number>)
      stmt.free()
      return row
    }
    stmt.free()
  }

  const normalized = ref.trim().replace(/\s+/g, ' ')
  const stmt = database.prepare(`
    SELECT id, book_id, chapter_id, chapter_num, page_num, para_num, reference, text
    FROM paragraphs
    WHERE UPPER(reference) = UPPER(?)
    LIMIT 1
  `)
  stmt.bind([normalized])
  if (stmt.step()) {
    const row = rowToParagraph(stmt.getAsObject() as Record<string, string | number>)
    stmt.free()
    return row
  }
  stmt.free()
  return null
}

export async function lookupByReference(ref: string): Promise<ParagraphRow | null> {
  await ensureEgwDb()
  const parsed = parseReference(ref)

  const egwHit = lookupInDb(egwDb!, ref, parsed)
  if (egwHit) return egwHit
  if (pioneerDb) return lookupInDb(pioneerDb, ref, parsed)
  return null
}

export { isPioneerBookId, PIONEER_PARAGRAPH_OFFSET }
export type { BookCollection }
